name: CI - Test and build Docker image

on:
  push:
    branches: [develop]
    paths:
      - "Sources/**"
      - "Tests/**"
      - Package.swift
  pull_request:
    branches: [develop]
    paths:
      - "Sources/**"
      - "Tests/**"
      - Package.swift

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup SSH Keys and known_hosts
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
      - name: Run tests
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: swift test # -v
