name: Unit tests

on:
  push:
    branches: [develop]
    paths:
      - "Sources/**"
      - "Tests/**"
      - Package.swift
  pull_request:
    branches: [develop]
    paths:
      - "Sources/**"
      - "Tests/**"
      - Package.swift

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup SSH Keys and known_hosts
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
      - name: Run tests
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          echo "disabled"
          # swift test # -v
      - name: Get repository metadata
        uses: varunsridharan/action-repository-meta@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout version repo
        uses: vweevers/multi-checkout-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repositories: |
            paulyhedral/sweetrpg-config
      - name: Get current version
        id: current_version
        run: |
          echo "::set-output name=version::$(cat ../paulyhedral/sweetrpg-config/Semver/${{ env.REPOSITORY_SLUG }})"
      - name: Increment patch version
        id: semver
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.current_version.outputs.version }}
      - name: Store new version
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          cd ../paulyhedral/sweetrpg-config
          echo "${{ steps.semver.outputs.version }}" > Semver/${{ env.REPOSITORY_SLUG }}
          git add Semver
          git commit -m "Update version for ${{ env.REPOSITORY_SLUG }}"
          git push
