name: Unit tests

on:
  push:
    branches: [develop]
    paths:
      - "src/**"
      - "tests/**"
      - setup.cfg
      - setup.py
      - "requirements/**"
  pull_request:
    branches: [develop]
    paths:
      - "src/**"
      - "tests/**"
      - setup.cfg
      - setup.py
      - "requirements/**"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9, 3.10-dev]
        os: [ubuntu-18.04, macOS-latest, windows-latest]
        include:
          # pypy3 on Mac OS currently fails trying to compile
          # brotlipy. Moving pypy3 to only test linux.
          - python-version: pypy3
            os: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup SSH Keys and known_hosts
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
      - name: Test packaging
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          python setup.py sdist bdist_wheel
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          make
      - name: Run tests
        run: |
          make ci
